import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpDown, Search } from "lucide-react";

import { PageHeader } from "@/components/crm/PageHeader";
import { DateRangeTabs, type DateSelection } from "@/components/crm/DateRangeTabs";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { publisherCps, trafficCalls, sales } from "@/lib/company-data";

export const Route = createFileRoute("/_shell/qa/reporting")({
  head: () => ({
    meta: [
      { title: "Publisher Sales Reporting — Policy Bear CRM" },
      {
        name: "description",
        content:
          "Publisher-level reporting: connected calls, valid sales, conversion performance, CPS, revenue and payout.",
      },
      { property: "og:title", content: "Publisher Sales Reporting — Policy Bear CRM" },
      {
        property: "og:description",
        content:
          "Publisher-level reporting: connected calls, valid sales, conversion performance, CPS, revenue and payout.",
      },
    ],
  }),
  component: QAReportingPage,
});

const money = (n: number) =>
  `$${n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

interface Row {
  name: string;
  connected: number;
  validSales: number;
  performance: number;
  cps: number;
  pubsCps: number;
  converted: number;
  duplicates: number;
  revenue: number;
  payout: number;
}

type SortKey = keyof Row;

function QAReportingPage() {
  const [date, setDate] = useState<DateSelection>({ preset: "month" });
  const [query, setQuery] = useState("");
  const [sortKey, setSortKey] = useState<SortKey>("connected");
  const [asc, setAsc] = useState(false);

  const rows = useMemo<Row[]>(() => {
    return publisherCps.map((c) => {
      const calls = trafficCalls.filter((t) => t.publisher === c.name);
      const connected = Math.max(c.converted, calls.length);
      const pubSales = sales.filter((s) => (s.publisher ?? "") === c.name);
      const revenue = pubSales.reduce((sum, s) => sum + s.premium, 0) || c.revenue;
      const seen = new Set<string>();
      let duplicates = 0;
      for (const t of calls) {
        if (seen.has(t.callerId)) duplicates += 1;
        else seen.add(t.callerId);
      }
      return {
        name: c.name,
        connected,
        validSales: c.validSales,
        performance: connected ? (c.validSales / connected) * 100 : 0,
        cps: c.validSales ? c.payout / c.validSales : 0,
        pubsCps: c.cps,
        converted: c.converted,
        duplicates,
        revenue,
        payout: c.payout,
      };
    });
  }, []);

  const visible = useMemo(() => {
    const q = query.trim().toLowerCase();
    const list = q ? rows.filter((r) => r.name.toLowerCase().includes(q)) : rows;
    return [...list].sort((a, b) => {
      const av = a[sortKey];
      const bv = b[sortKey];
      const cmp =
        typeof av === "string" && typeof bv === "string"
          ? av.localeCompare(bv)
          : (av as number) - (bv as number);
      return asc ? cmp : -cmp;
    });
  }, [rows, query, sortKey, asc]);

  const totals = useMemo(
    () =>
      visible.reduce(
        (t, r) => ({
          connected: t.connected + r.connected,
          validSales: t.validSales + r.validSales,
          converted: t.converted + r.converted,
          duplicates: t.duplicates + r.duplicates,
          revenue: t.revenue + r.revenue,
          payout: t.payout + r.payout,
        }),
        { connected: 0, validSales: 0, converted: 0, duplicates: 0, revenue: 0, payout: 0 },
      ),
    [visible],
  );

  const toggle = (key: SortKey) => {
    if (key === sortKey) setAsc((v) => !v);
    else {
      setSortKey(key);
      setAsc(false);
    }
  };

  const columns: { key: SortKey; label: string; align?: "right" }[] = [
    { key: "connected", label: "Connected Calls", align: "right" },
    { key: "validSales", label: "Valid Sales", align: "right" },
    { key: "performance", label: "Performance", align: "right" },
    { key: "cps", label: "CPS", align: "right" },
    { key: "pubsCps", label: "Pubs CPS", align: "right" },
    { key: "converted", label: "Converted", align: "right" },
    { key: "duplicates", label: "Duplicates", align: "right" },
    { key: "revenue", label: "Revenue", align: "right" },
    { key: "payout", label: "Payout", align: "right" },
  ];

  const perfTone = (p: number) =>
    p >= 30 ? "text-emerald-600" : p >= 10 ? "text-amber-600" : "text-destructive";

  return (
    <div className="space-y-4">
      <PageHeader
        title="Reporting"
        description="Sales generated by each publisher, with conversion performance and cost per sale."
      />

      <DateRangeTabs value={date} onChange={setDate} />

      <div className="inline-flex rounded-xl border bg-card p-1">
        <span className="rounded-lg bg-primary px-4 py-1.5 text-sm font-medium text-primary-foreground">
          Publisher
        </span>
      </div>

      <Card className="overflow-hidden p-0">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3">
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-semibold">Publisher</h2>
            <Badge variant="secondary">{visible.length}</Badge>
          </div>
          <div className="relative w-full max-w-xs">
            <Search className="pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search publishers"
              className="h-9 rounded-full pl-9"
            />
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full min-w-[1000px] text-sm">
            <thead className="bg-muted/50 text-xs uppercase tracking-wide text-muted-foreground">
              <tr>
                <th className="sticky left-0 z-10 bg-muted/50 px-4 py-2.5 text-left font-medium">
                  <button
                    className="inline-flex items-center gap-1"
                    onClick={() => toggle("name")}
                  >
                    Publisher <ArrowUpDown className="size-3" />
                  </button>
                </th>
                {columns.map((c) => (
                  <th key={c.key} className="whitespace-nowrap px-4 py-2.5 text-right font-medium">
                    <button
                      className="inline-flex items-center gap-1"
                      onClick={() => toggle(c.key)}
                    >
                      {c.label} <ArrowUpDown className="size-3" />
                    </button>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {visible.map((r, i) => (
                <tr
                  key={r.name}
                  className={cn(
                    "border-t transition-colors hover:bg-muted/40",
                    i % 2 === 1 && "bg-muted/20",
                  )}
                >
                  <td className="sticky left-0 z-10 max-w-[240px] truncate bg-card px-4 py-2.5 font-medium">
                    {r.name}
                  </td>
                  <td className="px-4 py-2.5 text-right tabular-nums text-primary">{r.connected}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums text-primary">{r.validSales}</td>
                  <td className={cn("px-4 py-2.5 text-right tabular-nums font-medium", perfTone(r.performance))}>
                    {r.performance.toFixed(2)} %
                  </td>
                  <td className="px-4 py-2.5 text-right tabular-nums">{money(r.cps)}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums">{money(r.pubsCps)}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums text-primary">{r.converted}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums">{r.duplicates}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums">{money(r.revenue)}</td>
                  <td className="px-4 py-2.5 text-right tabular-nums">{money(r.payout)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="border-t bg-muted/60 font-semibold">
                <td className="sticky left-0 z-10 bg-muted/60 px-4 py-2.5">Totals</td>
                <td className="px-4 py-2.5 text-right tabular-nums">{totals.connected}</td>
                <td className="px-4 py-2.5 text-right tabular-nums">{totals.validSales}</td>
                <td className="px-4 py-2.5 text-right tabular-nums">
                  {totals.connected ? ((totals.validSales / totals.connected) * 100).toFixed(2) : "0.00"} %
                </td>
                <td className="px-4 py-2.5 text-right tabular-nums">
                  {money(totals.validSales ? totals.payout / totals.validSales : 0)}
                </td>
                <td className="px-4 py-2.5" />
                <td className="px-4 py-2.5 text-right tabular-nums">{totals.converted}</td>
                <td className="px-4 py-2.5 text-right tabular-nums">{totals.duplicates}</td>
                <td className="px-4 py-2.5 text-right tabular-nums">{money(totals.revenue)}</td>
                <td className="px-4 py-2.5 text-right tabular-nums">{money(totals.payout)}</td>
              </tr>
            </tfoot>
          </table>
        </div>
      </Card>
    </div>
  );
}
