/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellBreakAlarmRouteImport } from './routes/_shell.break-alarm'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellAdminUsersRouteImport } from './routes/_shell.admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellBreakAlarmRoute = ShellBreakAlarmRouteImport.update({
  id: '/break-alarm',
  path: '/break-alarm',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminUsersRoute = ShellAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/break-alarm': typeof ShellBreakAlarmRoute
  '/dashboard': typeof ShellDashboardRoute
  '/admin/users': typeof ShellAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/break-alarm': typeof ShellBreakAlarmRoute
  '/dashboard': typeof ShellDashboardRoute
  '/admin/users': typeof ShellAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/break-alarm': typeof ShellBreakAlarmRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/admin/users': typeof ShellAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/break-alarm' | '/dashboard' | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/break-alarm' | '/dashboard' | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/break-alarm'
    | '/_shell/dashboard'
    | '/_shell/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/break-alarm': {
      id: '/_shell/break-alarm'
      path: '/break-alarm'
      fullPath: '/break-alarm'
      preLoaderRoute: typeof ShellBreakAlarmRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/users': {
      id: '/_shell/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ShellAdminUsersRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellBreakAlarmRoute: typeof ShellBreakAlarmRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellAdminUsersRoute: typeof ShellAdminUsersRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBreakAlarmRoute: ShellBreakAlarmRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellAdminUsersRoute: ShellAdminUsersRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
